[project]
name = "build-with-ai-workshop-2025"
version = "0.1.0"
description = "GDGC Build with AI Workshop"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "google>=3.0.0",
    "google-genai>=1.11.0",
]
